insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (1, 1, 'debit', 'Scotiabank', 5950.2, 719.32);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (2, 1, 'credit', 'Bank of Montreal (BMO)', 257.85, 437.06);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (3, 1, 'debit', 'Canadian Imperial Bank of Commerce (CIBC)', 9875.24, 0.00);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (4, 1, 'credit', 'Bank of Montreal (BMO)', 1251.78, 510.88);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (5, 1, 'credit', 'Bank of Montreal (BMO)', 7319.37, 506.78);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (6, 1, 'credit', 'Canadian Imperial Bank of Commerce (CIBC)', 2840.84, 606.61);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (7, 1, 'debit', 'HSBC Canada', 3013.14, 13.33);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (8, 1, 'credit', 'Canadian Imperial Bank of Commerce (CIBC)', 3046.11, 59.04);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (9, 1, 'credit', 'Canadian Imperial Bank of Commerce (CIBC)', 4751.09, 775.46);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (10, 2, 'credit', 'National Bank of Canada', 1996.18, 941.33);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (11, 2, 'debit', 'TD Canada Trust', 8005.25, 866.76);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (12, 2, 'credit', 'TD Canada Trust', 3786.31, 720.55);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (13, 2, 'debit', 'Bank of Montreal (BMO)', 8096.58, 824.95);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (14, 2, 'credit', 'Bank of Montreal (BMO)', 0.00, 546.47);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (15, 3, 'debit', 'Scotiabank', 7144.63, 439.97);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (16, 3, 'credit', 'Scotiabank', 0.00, 848.59);