insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (1, 1, 'debit', 'Scotiabank', 5950.2, 719.32);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (2, 13, 'credit', 'Bank of Montreal (BMO)', 257.85, 437.06);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (3, 8, 'debit', 'Canadian Imperial Bank of Commerce (CIBC)', 9875.24, 1.83);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (4, 20, 'credit', 'Bank of Montreal (BMO)', 1251.78, 510.88);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (5, 3, 'credit', 'Bank of Montreal (BMO)', 7319.37, 506.78);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (6, 2, 'credit', 'Canadian Imperial Bank of Commerce (CIBC)', 2840.84, 606.61);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (7, 28, 'debit', 'HSBC Canada', 3013.14, 13.33);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (8, 6, 'credit', 'Canadian Imperial Bank of Commerce (CIBC)', 3046.11, 59.04);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (9, 6, 'credit', 'Canadian Imperial Bank of Commerce (CIBC)', 4751.09, 775.46);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (10, 8, 'credit', 'National Bank of Canada', 1996.18, 941.33);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (11, 28, 'debit', 'TD Canada Trust', 8005.25, 866.76);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (12, 28, 'debit', 'Chase', 3786.31, 720.55);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (13, 28, 'credit', 'Bank of Montreal (BMO)', 8096.58, 824.95);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (14, 15, 'debit', 'HSBC Canada', 5621.71, 546.47);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (15, 10, 'debit', 'National Bank of Canada', 7144.63, 439.97);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (16, 27, 'credit', 'Bank of Montreal (BMO)', 4635.8, 848.59);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (17, 29, 'debit', 'Chase', 2333.39, 310.13);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (18, 18, 'debit', 'Royal Bank of Canada (RBC)', 8189.68, 745.86);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (19, 18, 'credit', 'Canadian Imperial Bank of Commerce (CIBC)', 8121.4, 978.28);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (20, 17, 'debit', 'TD Canada Trust', 3992.93, 745.26);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (21, 26, 'credit', 'HSBC Canada', 841.02, 272.52);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (22, 2, 'credit', 'Canadian Imperial Bank of Commerce (CIBC)', 8338.45, 851.94);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (23, 10, 'debit', 'Canadian Imperial Bank of Commerce (CIBC)', 7534.68, 192.33);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (24, 16, 'credit', 'HSBC Canada', 1758.06, 411.81);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (25, 8, 'debit', 'HSBC Canada', 5647.73, 821.51);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (26, 27, 'credit', 'Chase', 2020.46, 177.28);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (27, 30, 'credit', 'HSBC Canada', 1082.59, 279.51);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (28, 5, 'credit', 'Canadian Imperial Bank of Commerce (CIBC)', 2559.07, 125.12);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (29, 16, 'debit', 'HSBC Canada', 7004.19, 972.26);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (30, 22, 'debit', 'Royal Bank of Canada (RBC)', 9700.62, 232.61);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (31, 13, 'debit', 'Scotiabank', 1444.83, 163.06);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (32, 1, 'credit', 'Scotiabank', 7235.79, 281.58);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (33, 16, 'debit', 'Chase', 6260.29, 205.5);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (34, 29, 'credit', 'Scotiabank', 2980.49, 887.89);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (35, 25, 'credit', 'Canadian Imperial Bank of Commerce (CIBC)', 6070.31, 997.7);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (36, 29, 'debit', 'TD Canada Trust', 4408.02, 522.91);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (37, 19, 'debit', 'Canadian Imperial Bank of Commerce (CIBC)', 5666.0, 388.81);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (38, 24, 'debit', 'Bank of Montreal (BMO)', 4881.79, 36.43);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (39, 29, 'debit', 'Scotiabank', 3180.05, 179.29);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (40, 25, 'credit', 'Chase', 4939.77, 456.38);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (41, 7, 'credit', 'Bank of Montreal (BMO)', 1371.02, 765.83);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (42, 21, 'debit', 'Chase', 3718.23, 589.87);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (43, 15, 'debit', 'TD Canada Trust', 6643.46, 758.56);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (44, 24, 'debit', 'HSBC Canada', 7949.44, 866.9);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (45, 10, 'credit', 'TD Canada Trust', 6877.08, 362.52);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (46, 9, 'debit', 'HSBC Canada', 8189.44, 24.73);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (47, 6, 'credit', 'Royal Bank of Canada (RBC)', 8276.78, 944.06);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (48, 8, 'credit', 'Royal Bank of Canada (RBC)', 6251.69, 179.86);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (49, 5, 'credit', 'Chase', 120.5, 740.68);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (50, 4, 'credit', 'National Bank of Canada', 6108.69, 734.03);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (51, 11, 'debit', 'TD Canada Trust', 6985.32, 136.58);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (52, 12, 'credit', 'TD Canada Trust', 1000.00, 0.00);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (53, 14, 'debit', 'Scotiabank', 5000.00, 99.65);
insert into account (account_id, account_user_id, account_type, bank, have_amount, owe_amount) values (54, 23, 'debit', 'Royal Bank of Canada (RBC)', 15000.00, 26.30);